version: '3.7'
services:
    frontend:
        build:
            context: ./frontend-ng
        container_name: 'bpc-ng-frontend'
        restart: unless-stopped
        networks:
            - reverse-proxy
    pocketbase:
        build:
            context: ./pocketbase
        container_name: 'bpc-ng-pocketbase'
        restart: unless-stopped
        volumes:
            - ./data:/pb_data
        # ports:
        #     - '8090:8090'
        networks:
            - back
            - reverse-proxy
        healthcheck:
            test: wget --no-verbose --tries=1 --spider http://bpc-ng-pocketbase:8090/api/health || exit 1
            interval: 10s
            timeout: 10s
            retries: 3
    sync:
        build:
            context: ./sync-service-sse
        container_name: 'bpc-ng-sync'
        restart: unless-stopped
        environment:
            - PB_URL=http://bpc-ng-pocketbase:8090/
            - PB_USER=
            - PB_PASSWD=
            - CLIENT_SECRET=
            - CLIENT_ID=
        networks:
            - reverse-proxy
            - back
    ical:
        build:
            context: ./ical-service
        container_name: 'bpc-ng-ical'
        restart: unless-stopped
        environment:
            - PB_URL=http://bpc-ng-pocketbase:8090/
            - PB_USER=
            - PB_PASSWD=
        networks:
            - reverse-proxy
            - back
networks:
    back:
        driver: bridge
    reverse-proxy:
        external:
            name: reverse-proxy
