name: Build & Push Docker Image
run-name: Build & Push
on: 
  workflow_call:
    inputs:
      docker-image-name:
        required: true
        type: string
      context: 
        required: true
        type: string
      build-args:
        required: false
        type: string

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ inputs.docker-image-name }}
            ghcr.io/${{ inputs.docker-image-name }}
          tags: |
            type=sha,format=short,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=develop,enable=${{ github.ref == format('refs/heads/{0}', 'develop') }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          push: true
          build-args: ${{ inputs.build-args }}
          tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  