name: Docker Image CI
on: push
env:
  PB_VERSION: 0.11.3
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: | 
          docker build \
          --build-arg UI_VERSION=$GITHUB_SHA \
          --build-arg PB_VERSION=$PB_VERSION \
          .

          