name: Build & Deploy Services
run-name: Build & Deploy Services
on: 
  push:
    branches:
      - main
      - develop

jobs:
  check:
    name: "Prepare" 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          # base: ${{ github.ref }}
          filters: .github/filters.yml
      - name: Get Short SHA
        id: vars
        run: |
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    outputs:
      sync: ${{ steps.filter.outputs.sync == 'true' }}
      frontend: ${{ steps.filter.outputs.frontend }}
      ical: ${{ steps.filter.outputs.ical }}
      workflows: ${{ steps.filter.outputs.workflows }}
      short_sha: ${{ steps.vars.outputs.short_sha}}
  build-frontend:
    name: "Frontend"
    needs: check
    if: needs.check.outputs.frontend == 'true'
    uses: ./.github/workflows/build.yml
    with:
      docker-image-name: "jonas-ponas/expert-giggle-frontend"
      context: ./frontend/
      build-args: |
        UI_VERSION=${{ needs.check.outputs.short_sha }}
        PB_VERSION=${{ vars.PB_VERSION }}
    secrets: inherit
  build-sync:
    name: "Sync-Service"
    needs: check
    if: needs.check.outputs.sync == 'true'
    uses: ./.github/workflows/build.yml
    with:
      docker-image-name: "jonas-ponas/expert-giggle"
      context: ./sync-service/
    secrets: inherit
  build-ical:
    name: "ical-Service"
    needs: check
    if: needs.check.outputs.ical == 'true'
    uses: ./.github/workflows/build.yml
    with:
      docker-image-name: "jonas-ponas/bpc-ical-service"
      context: ./ical-service/
    secrets: inherit
  deploy:
    name: "Deploy"
    needs: 
      - build-frontend
      - build-sync
      - build-ical
    if: |
      always() && 
      (needs.build-frontend.result == 'success' || needs.build-sync.result == 'success' || needs.build-ical.result == 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Call Watchtower
        run: |
          curl -H "Authorization: Bearer ${{secrets.WATCHTOWER_TOKEN}}" ${{secrets.WATCHTOWER_ENDPOINT}}