name: Build and Deploy Frontend
on: 
  push:
    paths:
      - "frontend/**"
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  PB_VERSION: 0.13
  
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version id 
        id: vars
        run: |
          echo "version_id=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: haya14busa/action-cond@v1
        id: docker_tag
        with:
          cond: ${{ github.ref == 'refs/heads/main' }}
          if_true: "latest"
          if_false: "develop"
      - name: Build image
        if: success()
        run: | 
          docker build \
          --build-arg UI_VERSION=${{steps.vars.outputs.version_id}} \
          --build-arg PB_VERSION=$PB_VERSION \
          -t ghcr.io/jonas-ponas/expert-giggle-frontend:${{steps.vars.outputs.version_id}} \
          -t ghcr.io/jonas-ponas/expert-giggle-frontend:${{steps.docker_tag.outputs.value}} \
          ./frontend/
      - name: Push image
        if: success()
        run: |
          docker push -a ghcr.io/jonas-ponas/expert-giggle-frontend
      - name: Call Watchtower
        if: success()
        run: |
          curl -H "Authorization: Bearer ${{secrets.WATCHTOWER_TOKEN}}" ${{secrets.WATCHTOWER_ENDPOINT}}
