name: Build and Deploy sync-service

on:
  push:
    paths:
      - "sync-service/**"
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - uses: haya14busa/action-cond@v1
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' # Only push if on main
      id: docker_tag
      with:
        cond: ${{ github.ref == 'refs/heads/main' }}
        if_true: "latest"
        if_false: "develop"
    - name: Build image
      run: | 
        docker build \
        -t ghcr.io/jonas-ponas/expert-giggle:${{steps.vars.outputs.sha_short}} \
        -t ghcr.io/jonas-ponas/expert-giggle:${{steps.docker_tag.outputs.value}} \
        ./sync-service/
    - name: Push the Docker image
      run: docker push ghcr.io/jonas-ponas/expert-giggle:latest
    
